(function financeOrganizer(){
'use strict';

const ADVANCE_SECTION_ID='accountingNotesSection';
const MAINTENANCE_SECTION_ID='maintenanceInstallmentsSection';
const SALARY_SECTION_ID='workerSalariesSection';
const HUB_ID='financeEntryHub';
const Core=window.ResortAccountCore;
const uid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const today=()=>typeof window.isoToday==='function'?window.isoToday():new Date().toISOString().slice(0,10);
const esc=value=>typeof window.escapeHtml==='function'?window.escapeHtml(String(value??'')):String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>typeof window.money==='function'?window.money(Number(value||0)):new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2}).format(Number(value||0))+' ر.س';
const parseAmount=value=>Core?.parseMoney?Core.parseMoney(value):(window.AdwaaNumberInput?.parseNumber?.(value,0)??Number(value||0));
const clone=value=>typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value));

function notes(){if(!Array.isArray(db.accountingNotes))db.accountingNotes=[];return db.accountingNotes;}
function maintenanceJobs(){if(!Array.isArray(db.maintenanceJobs))db.maintenanceJobs=[];return db.maintenanceJobs;}
function expenses(){if(!Array.isArray(db.expenses))db.expenses=[];return db.expenses;}
function payments(note){return (Array.isArray(note?.payments)?note.payments:[]).map(row=>({...row,amount:Math.max(0,parseAmount(row?.amount))}));}
function summary(note){
  const principal=Math.max(0,parseAmount(note?.principalAmount??note?.totalAmount));
  const paid=payments(note).reduce((sum,row)=>sum+row.amount,0);
  return {principal,paid,remaining:Math.max(0,principal-paid)};
}
function addAudit(action,entity,details,before,after){window.addAudit?.(action,entity,details,before,after);}
function openModal(id){document.getElementById(id)?.classList.add('open');document.body.classList.add('modal-open');}
function closeModal(id){window.closeModal?.(id);}
function expenseReference(){const values=expenses().map(row=>Number(String(row.ref||'').match(/\d+/)?.[0]||0));return 'EXP-'+String(Math.max(0,...values)+1).padStart(4,'0');}
function findMaintenanceExpense(paymentId){return expenses().filter(row=>row.maintenancePaymentId===paymentId);}
function findJob(jobId){return maintenanceJobs().find(row=>row.id===jobId)||null;}
function findNote(noteId){return notes().find(row=>row.id===noteId)||null;}
function isSalary(row){return row?.expenseType==='salary'||!!row?.salaryMonth||row?.category==='راتب عامل'||row?.cat==='راتب عامل';}
function findSalary(expenseId){return expenses().find(row=>row.id===expenseId&&isSalary(row))||null;}
function workerNameKey(value){return String(value||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('ar');}

async function persistFinance(){
  if(typeof window.persist==='function')await window.persist();
  window.renderResortAccount?.();
  if(typeof window.renderExpenses==='function')window.renderExpenses();
  renderAllFinanceTools();
}

function preserveMaintenanceState(){
  if(!Array.isArray(db.maintenanceJobs))db.maintenanceJobs=[];
  const current=window.normalizeDB;
  if(typeof current!=='function'||current.__maintenanceStatePreserved)return;
  const wrapped=function(value){
    const source=value&&typeof value==='object'?value:{};
    const normalized=current(source);
    normalized.maintenanceJobs=Array.isArray(source.maintenanceJobs)?source.maintenanceJobs:[];
    return normalized;
  };
  wrapped.__maintenanceStatePreserved=true;
  wrapped.__baseNormalizeDB=current;
  window.normalizeDB=wrapped;
  try{normalizeDB=wrapped}catch(error){console.warn('تعذر تفعيل حفظ مستحقات الصيانة',error)}
}

function installStyles(){
  if(document.getElementById('financeOrganizerStyles'))return;
  const style=document.createElement('style');style.id='financeOrganizerStyles';style.textContent=`
  .finance-entry-hub{padding:16px 18px}.finance-entry-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.finance-entry-btn{border:1px solid var(--line);background:#f8faf9;border-radius:15px;padding:14px;text-align:right;min-height:86px}.finance-entry-btn b{display:block;font-size:14px;margin-bottom:5px}.finance-entry-btn span{font-size:11px;color:var(--muted);line-height:1.6}.finance-entry-btn.primary-entry{background:#0d4c3f;color:#fff}.finance-entry-btn.primary-entry span{color:#d8e7e2}
  .finance-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:11px}.finance-kpi{border:1px solid var(--line);border-radius:13px;padding:11px;background:#fff}.finance-kpi span{display:block;color:var(--muted);font-size:11px}.finance-kpi b{display:block;margin-top:4px}.fo-list{display:grid;gap:9px;padding:14px 18px 18px}.fo-card{border:1px solid var(--line);border-radius:16px;padding:13px;background:#fff}.fo-card.settled{background:#f4fbf7;border-color:#acd7c4}.fo-head{display:flex;justify-content:space-between;gap:10px}.fo-status{font-size:11px;font-weight:900;padding:6px 9px;border-radius:999px;background:#fff3d9;color:#8b6500;height:max-content}.settled .fo-status{background:#e4f4ee;color:#14785f}.fo-figures{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:10px 0}.fo-figure{background:#fafcfb;border:1px solid var(--line);border-radius:11px;padding:9px}.fo-figure span{display:block;color:var(--muted);font-size:10px}.fo-payment{display:flex;justify-content:space-between;gap:8px;padding:8px 0;border-top:1px solid #edf0ee}.fo-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.fo-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:14px 18px 0}.fo-summary>div{border:1px solid var(--line);border-radius:12px;padding:10px}.fo-summary span{display:block;color:var(--muted);font-size:10px}.fo-summary b{display:block;margin-top:4px}.fo-modal .sheet{max-width:650px;margin:auto}.fo-source{display:inline-flex;padding:3px 7px;border-radius:999px;background:#eef3f1;color:#315a50;font-size:10px;margin-inline-start:5px}
  @media(max-width:720px){.finance-entry-grid{grid-template-columns:1fr 1fr}.finance-kpis,.fo-summary,.fo-figures{grid-template-columns:1fr}.fo-head,.fo-payment{flex-direction:column}.finance-entry-btn{min-height:76px}}
  `;document.head.appendChild(style);
}

function installHub(){
  const finance=document.getElementById('expenses');if(!finance||document.getElementById(HUB_ID))return;
  const section=document.createElement('div');section.className='section';section.id=HUB_ID;
  section.innerHTML=`<div class="section-head"><div><h3>💳 مركز التسجيل المالي</h3><div class="meta">اختر مصدر الحركة حتى يظهر أثرها مرة واحدة وبوصف واضح.</div></div></div><div class="finance-entry-hub"><div class="finance-entry-grid"><button class="finance-entry-btn primary-entry" type="button" onclick="openExpense()"><b>🧾 مصروف عادي</b><span>مشتريات وخدمات تشغيلية</span></button><button class="finance-entry-btn" type="button" onclick="openMaintenanceJob()"><b>🛠️ صيانة/مستحقات</b><span>التزام ودفعات فعلية ومتـبقي</span></button><button class="finance-entry-btn" type="button" onclick="openSalaryExpense()"><b>👷 تسجيل راتب عامل</b><span>العامل والشهر وتاريخ الدفع</span></button><button class="finance-entry-btn" type="button" onclick="openAccountingNote()"><b>↔️ سلفة من حساب المنتجع</b><span>تخرج من الرصيد وتعود عند السداد</span></button></div><div class="finance-kpis"><div class="finance-kpi"><span>المصروفات الفعلية</span><b id="foActualExpenses">0</b></div><div class="finance-kpi"><span>رواتب الشهر</span><b id="foSalaryMonth">0</b></div><div class="finance-kpi"><span>رواتب السنة</span><b id="foSalaryYear">0</b></div><div class="finance-kpi"><span>المدفوع للصيانة</span><b id="foMaintenancePaid">0</b></div><div class="finance-kpi"><span>مستحقات الصيانة المتبقية</span><b id="foMaintenanceDue">0</b></div><div class="finance-kpi"><span>السلف القائمة / العائد منها</span><b><span id="foAdvanceDue">0</span> / <span id="foAdvanceReturned">0</span></b></div></div></div>`;
  finance.prepend(section);
}

function installSections(){
  const finance=document.getElementById('expenses');if(!finance)return;
  if(!document.getElementById(MAINTENANCE_SECTION_ID)){
    const section=document.createElement('div');section.className='section';section.id=MAINTENANCE_SECTION_ID;
    section.innerHTML=`<div class="section-head"><div><h3>🛠️ مستحقات الصيانة</h3><div class="meta">إنشاء الصيانة لا يخصم من الرصيد؛ كل دفعة فعلية تُسجل كمصروف مرة واحدة فقط.</div></div><button class="primary" type="button" onclick="openMaintenanceJob()">+ صيانة جديدة</button></div><div class="fo-summary"><div><span>إجمالي الصيانة</span><b id="maintTotal">0</b></div><div><span>المدفوع فعليًا</span><b id="maintPaid">0</b></div><div><span>المتبقي</span><b id="maintDue">0</b></div></div><div id="maintenanceList" class="fo-list"></div>`;
    finance.appendChild(section);
  }
  if(!document.getElementById(SALARY_SECTION_ID)){
    const section=document.createElement('div');section.className='section';section.id=SALARY_SECTION_ID;
    section.innerHTML=`<div class="section-head"><div><h3>👷 رواتب العامل</h3><div class="meta">سجل الرواتب المدفوعة فعليًا حسب العامل والشهر.</div></div><button class="primary" type="button" onclick="openSalaryExpense()">تسجيل راتب عامل</button></div><div class="fo-summary"><div><span>إجمالي الشهر</span><b id="salaryMonthTotal">0</b></div><div><span>إجمالي السنة</span><b id="salaryYearTotal">0</b></div><div><span>عدد دفعات السنة</span><b id="salaryYearCount">0</b></div></div><div id="salaryList" class="fo-list"></div>`;
    finance.appendChild(section);
  }
  if(!document.getElementById(ADVANCE_SECTION_ID)){
    const section=document.createElement('div');section.className='section';section.id=ADVANCE_SECTION_ID;
    section.innerHTML=`<div class="section-head"><div><h3>↔️ السلف والذمم</h3><div class="meta">هذه المبالغ ليست مصروفًا ولا تغيّر صافي الربح؛ تخصم من رصيد حساب المنتجع، وكل سداد يعيد المبلغ إلى الرصيد تلقائيًا.</div></div><button class="primary" type="button" onclick="openAccountingNote()">+ سلفة</button></div><div class="fo-summary"><div><span>أصل المبلغ</span><b id="advTotal">0</b></div><div><span>إجمالي ما تم سداده</span><b id="advPaid">0</b></div><div><span>المتبقي لحساب المنتجع</span><b id="advDue">0</b></div></div><div id="accountingNotesList" class="fo-list"></div>`;
    finance.appendChild(section);
  }
}

function installModals(){
  if(!document.getElementById('maintenanceJobModal')){
    document.body.insertAdjacentHTML('beforeend',`<div class="modal fo-modal" id="maintenanceJobModal"><div class="sheet"><div class="sheet-head"><h2 id="maintenanceJobModalTitle">صيانة/مستحق جديد</h2><button class="close" type="button" onclick="closeModal('maintenanceJobModal')">×</button></div><form id="maintenanceJobForm"><input type="hidden" name="id"><div class="form-grid"><label>اسم الصيانة/العمل<input name="title" required maxlength="120"></label><label>الفني أو المستفيد<input name="vendor" required maxlength="120"></label><label>إجمالي التكلفة<input name="total" type="number" min="0.01" step="0.01" inputmode="decimal" required></label><label>تاريخ العمل<input name="date" type="date" required></label><label class="full">ملاحظات<textarea name="note" maxlength="1200"></textarea></label></div><div class="actions"><button class="secondary" type="button" onclick="closeModal('maintenanceJobModal')">إلغاء</button><button class="primary" type="submit">حفظ</button></div></form></div></div><div class="modal fo-modal" id="maintenancePaymentModal"><div class="sheet"><div class="sheet-head"><h2 id="maintenancePaymentModalTitle">إضافة دفعة صيانة</h2><button class="close" type="button" onclick="closeModal('maintenancePaymentModal')">×</button></div><form id="maintenancePaymentForm"><input type="hidden" name="jobId"><input type="hidden" name="paymentId"><div class="form-grid"><label>المبلغ<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label><label>التاريخ<input name="date" type="date" required></label><label class="full">ملاحظة الدفعة<input name="note" maxlength="500"></label></div><div class="actions"><button class="secondary" type="button" onclick="closeModal('maintenancePaymentModal')">إلغاء</button><button class="primary" type="submit">حفظ الدفعة</button></div></form></div></div>`);
    document.getElementById('maintenanceJobForm').addEventListener('submit',saveMaintenanceJob);document.getElementById('maintenancePaymentForm').addEventListener('submit',saveMaintenancePayment);
  }
  if(!document.getElementById('salaryExpenseModal')){
    document.body.insertAdjacentHTML('beforeend',`<div class="modal fo-modal" id="salaryExpenseModal"><div class="sheet"><div class="sheet-head"><h2 id="salaryExpenseModalTitle">تسجيل راتب عامل</h2><button class="close" type="button" onclick="closeModal('salaryExpenseModal')">×</button></div><form id="salaryExpenseForm"><input type="hidden" name="id"><div class="form-grid"><label>اسم العامل<input name="worker" required maxlength="120"></label><label>شهر الراتب<input name="month" type="month" required></label><label>مبلغ الراتب<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label><label>تاريخ الدفع<input name="date" type="date" required></label><label class="full">ملاحظات<textarea name="note" maxlength="800"></textarea></label></div><div class="actions"><button class="secondary" type="button" onclick="closeModal('salaryExpenseModal')">إلغاء</button><button class="danger" id="deleteSalaryBtn" type="button" onclick="deleteSalaryExpense()" style="display:none">حذف</button><button class="primary" type="submit">حفظ الراتب</button></div></form></div></div>`);
    document.getElementById('salaryExpenseForm').addEventListener('submit',saveSalaryExpense);
  }
  if(!document.getElementById('accountingNoteModal')){
    document.body.insertAdjacentHTML('beforeend',`<div class="modal fo-modal" id="accountingNoteModal"><div class="sheet"><div class="sheet-head"><h2 id="accountingNoteModalTitle">ملاحظة حسابية / سلفة</h2><button class="close" type="button" onclick="closeModal('accountingNoteModal')">×</button></div><form id="accountingNoteForm"><input type="hidden" name="id"><div class="form-grid"><label>العنوان<input name="title" required maxlength="120"></label><label>أصل المبلغ<input name="principalAmount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label><label>التاريخ<input name="date" type="date" required></label><label class="full">الملاحظة<textarea name="note" maxlength="1200"></textarea></label></div><div class="actions"><button class="secondary" type="button" onclick="closeModal('accountingNoteModal')">إلغاء</button><button class="primary" type="submit">حفظ</button></div></form></div></div><div class="modal fo-modal" id="accountingPaymentModal"><div class="sheet"><div class="sheet-head"><h2 id="accountingPaymentModalTitle">إضافة سداد</h2><button class="close" type="button" onclick="closeModal('accountingPaymentModal')">×</button></div><form id="accountingPaymentForm"><input type="hidden" name="noteId"><input type="hidden" name="paymentId"><div class="form-grid"><label>مبلغ السداد<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label><label>التاريخ<input name="date" type="date" required></label><label class="full">ملاحظة السداد<input name="note" maxlength="500"></label></div><div class="actions"><button class="secondary" type="button" onclick="closeModal('accountingPaymentModal')">إلغاء</button><button class="primary" type="submit">حفظ السداد</button></div></form></div></div>`);
    document.getElementById('accountingNoteForm').addEventListener('submit',saveAccountingNote);document.getElementById('accountingPaymentForm').addEventListener('submit',saveAccountingPayment);
  }
  window.AdwaaNumberInput?.scan?.(document);
}

function setMoney(id,value){const element=document.getElementById(id);if(element)element.textContent=money(value);}
function renderHub(){
  const month=today().slice(0,7),year=month.slice(0,4),financial=Core?.financeSummary?.(db)||{actualExpenses:0,maintenancePaid:0,maintenanceDue:0,outstanding:0,repaid:0};
  setMoney('foActualExpenses',financial.actualExpenses);setMoney('foMaintenancePaid',financial.maintenancePaid);setMoney('foMaintenanceDue',financial.maintenanceDue);setMoney('foAdvanceDue',financial.outstanding);setMoney('foAdvanceReturned',financial.repaid);setMoney('foSalaryMonth',Core?.salaryTotals?.(db,{month}).amount||0);setMoney('foSalaryYear',Core?.salaryTotals?.(db,{year}).amount||0);
}
function renderMaintenance(){
  const list=document.getElementById('maintenanceList');if(!list)return;const totals=maintenanceJobs().reduce((acc,job)=>{const item=summary(job);acc.total+=item.principal;acc.paid+=item.paid;acc.remaining+=item.remaining;return acc;},{total:0,paid:0,remaining:0});setMoney('maintTotal',totals.total);setMoney('maintPaid',totals.paid);setMoney('maintDue',totals.remaining);
  list.innerHTML=[...maintenanceJobs()].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).map(job=>{const item=summary(job),settled=item.remaining<=0.009,status=item.paid<=0?'غير مدفوع':settled?'مسدد بالكامل':'مدفوع جزئيًا',rows=payments(job).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));return `<article class="fo-card ${settled?'settled':''}"><div class="fo-head"><div><b>${esc(job.title||'صيانة')}</b><span class="fo-source">صيانة</span><div class="meta">${esc(job.vendor||'—')} • ${esc(job.date||'—')}${job.note?' • '+esc(job.note):''}</div></div><span class="fo-status">${status}${settled?'':' — متبقي '+money(item.remaining)}</span></div><div class="fo-figures"><div class="fo-figure"><span>إجمالي الصيانة</span><b>${money(item.principal)}</b></div><div class="fo-figure"><span>المدفوع</span><b>${money(item.paid)}</b></div><div class="fo-figure"><span>المتبقي</span><b>${money(item.remaining)}</b></div></div>${rows.length?rows.map(row=>`<div class="fo-payment"><div><b>${money(row.amount)}</b><div class="meta">${esc(row.date||'—')}${row.note?' • '+esc(row.note):''}</div></div><div><button class="secondary small" type="button" onclick="openMaintenancePayment('${esc(job.id)}','${esc(row.id)}')">تعديل</button> <button class="danger small" type="button" onclick="deleteMaintenancePayment('${esc(job.id)}','${esc(row.id)}')">حذف</button></div></div>`).join(''):'<div class="meta">لم تُسجل دفعات بعد؛ لا يوجد خصم من الرصيد.</div>'}<div class="fo-actions">${settled?'':`<button class="primary" type="button" onclick="openMaintenancePayment('${esc(job.id)}')">+ إضافة دفعة</button>`}<button class="secondary" type="button" onclick="openMaintenanceJob('${esc(job.id)}')">تعديل الصيانة</button>${rows.length?'':`<button class="danger" type="button" onclick="deleteMaintenanceJob('${esc(job.id)}')">حذف</button>`}</div></article>`;}).join('')||'<div class="empty">لا توجد مستحقات صيانة.</div>';
}
function renderSalaries(){
  const list=document.getElementById('salaryList');if(!list)return;const month=today().slice(0,7),year=month.slice(0,4),rows=Core?.salaryRows?.(db)||expenses().filter(row=>row.expenseType==='salary'),monthTotals=Core?.salaryTotals?.(db,{month})||{amount:0},yearTotals=Core?.salaryTotals?.(db,{year})||{amount:0,count:0};setMoney('salaryMonthTotal',monthTotals.amount);setMoney('salaryYearTotal',yearTotals.amount);const count=document.getElementById('salaryYearCount');if(count)count.textContent=String(yearTotals.count||0);
  const groups=new Map();for(const row of rows){const key=workerNameKey(row.workerName||String(row.title||'').replace(/^راتب العامل:\s*/,''))||'عامل غير محدد';if(!groups.has(key))groups.set(key,{name:row.workerName||String(row.title||'').replace(/^راتب العامل:\s*/,''),rows:[]});groups.get(key).rows.push(row);}
  list.innerHTML=[...groups.values()].sort((a,b)=>a.name.localeCompare(b.name,'ar')).map(group=>`<article class="fo-card"><div class="fo-head"><div><b>${esc(group.name)}</b><span class="fo-source">راتب عامل</span><div class="meta">الأشهر المدفوعة: ${group.rows.map(row=>esc(row.salaryMonth||String(row.date||'').slice(0,7))).sort().join('، ')}</div></div><b>${money(group.rows.reduce((sum,row)=>sum+parseAmount(row.amount),0))}</b></div>${group.rows.sort((a,b)=>String(b.salaryMonth||b.date).localeCompare(String(a.salaryMonth||a.date))).map(row=>`<div class="fo-payment"><div><b>${money(row.amount)}</b><div class="meta">شهر ${esc(row.salaryMonth||'—')} • دفع ${esc(row.date||'—')}${row.notes?' • '+esc(row.notes):''}${row.intentionalDuplicate?' • تكرار مقصود':''}</div></div><button class="secondary small" type="button" onclick="openSalaryExpense('${esc(row.id)}')">تعديل</button></div>`).join('')}</article>`).join('')||'<div class="empty">لا توجد رواتب مسجلة.</div>';
}
function renderAdvances(){
  const list=document.getElementById('accountingNotesList');if(!list)return;const totals=notes().reduce((acc,note)=>{const item=summary(note);acc.principal+=item.principal;acc.paid+=item.paid;acc.remaining+=item.remaining;return acc;},{principal:0,paid:0,remaining:0});setMoney('advTotal',totals.principal);setMoney('advPaid',totals.paid);setMoney('advDue',totals.remaining);
  list.innerHTML=[...notes()].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).map(note=>{const item=summary(note),settled=item.remaining<=0.009,rows=payments(note);return `<article class="fo-card ${settled?'settled':''}"><div class="fo-head"><div><b>${esc(note.title||'سلفة')}</b><span class="fo-source">سلفة</span><div class="meta">${esc(note.date||'—')}${note.note?' • '+esc(note.note):''}</div></div><span class="fo-status">${settled?'مسدد بالكامل':'متبقي '+money(item.remaining)}</span></div><div class="fo-figures"><div class="fo-figure"><span>أصل المبلغ</span><b>${money(item.principal)}</b></div><div class="fo-figure"><span>إجمالي ما تم سداده</span><b>${money(item.paid)}</b></div><div class="fo-figure"><span>المتبقي لحساب المنتجع</span><b>${money(item.remaining)}</b></div></div>${rows.map(row=>`<div class="fo-payment"><div><b>${money(row.amount)}</b><div class="meta">${esc(row.date||'—')}${row.note?' • '+esc(row.note):''}</div></div><div><button class="secondary small" type="button" onclick="openAccountingPayment('${esc(note.id)}','${esc(row.id)}')">تعديل</button> <button class="danger small" type="button" onclick="deleteAccountingPayment('${esc(note.id)}','${esc(row.id)}')">حذف</button></div></div>`).join('')}<div class="fo-actions">${settled?'':`<button class="primary" type="button" onclick="openAccountingPayment('${esc(note.id)}')">+ تسجيل سداد</button>`}<button class="secondary" type="button" onclick="openAccountingNote('${esc(note.id)}')">تعديل</button><button class="danger" type="button" onclick="deleteAccountingNote('${esc(note.id)}')">حذف</button></div></article>`;}).join('')||'<div class="empty">لا توجد سلف أو ذمم.</div>';
}
function renderAllFinanceTools(){installHub();installSections();installModals();renderHub();renderMaintenance();renderSalaries();renderAdvances();}

function openMaintenanceJob(id=''){installModals();const job=id?findJob(id):null,form=document.getElementById('maintenanceJobForm');form.reset();form.elements.id.value=job?.id||'';form.elements.title.value=job?.title||'';form.elements.vendor.value=job?.vendor||'';form.elements.total.value=job?.totalAmount??'';form.elements.date.value=job?.date||today();form.elements.note.value=job?.note||'';document.getElementById('maintenanceJobModalTitle').textContent=job?'تعديل الصيانة':'صيانة/مستحق جديد';openModal('maintenanceJobModal');}
async function saveMaintenanceJob(event){event.preventDefault();const form=event.currentTarget,id=form.elements.id.value,job=id?findJob(id):null,totalAmount=Math.max(0,parseAmount(form.elements.total.value)),alreadyPaid=job?summary(job).paid:0;if(!(totalAmount>0)){alert('أدخل إجمالي تكلفة الصيانة.');return}if(totalAmount+0.009<alreadyPaid){alert(`لا يمكن جعل إجمالي الصيانة أقل من المدفوع (${money(alreadyPaid)}).`);return}const next={id:job?.id||uid(),title:String(form.elements.title.value||'').trim(),vendor:String(form.elements.vendor.value||'').trim(),totalAmount,date:form.elements.date.value||today(),note:String(form.elements.note.value||'').trim(),payments:payments(job),createdAt:job?.createdAt||now(),updatedAt:now()},before=job?clone(job):null;if(job)Object.assign(job,next);else maintenanceJobs().push(next);addAudit(job?'تعديل':'إضافة','مستحق صيانة',`${next.title} — ${next.vendor} — ${money(totalAmount)}`,before,next);closeModal('maintenanceJobModal');await persistFinance();}
async function deleteMaintenanceJob(id){const job=findJob(id);if(!job)return;if(payments(job).length){alert('لا يمكن حذف صيانة لها دفعات فعلية. احذف الدفعات من سجلها أولًا حتى يبقى الأثر المالي واضحًا.');return}if(!confirm('حذف مستحق الصيانة الذي لم تُسجل عليه أي دفعة؟'))return;db.maintenanceJobs=maintenanceJobs().filter(row=>row.id!==id);addAudit('حذف','مستحق صيانة',job.title||'',job,null);await persistFinance();}
function openMaintenancePayment(jobId,paymentId=''){installModals();const job=findJob(jobId);if(!job)return;const payment=payments(job).find(row=>row.id===paymentId)||null,form=document.getElementById('maintenancePaymentForm');form.reset();form.elements.jobId.value=jobId;form.elements.paymentId.value=payment?.id||'';form.elements.amount.value=payment?.amount??'';form.elements.date.value=payment?.date||today();form.elements.note.value=payment?.note||'';document.getElementById('maintenancePaymentModalTitle').textContent=payment?'تعديل دفعة الصيانة':'إضافة دفعة صيانة';openModal('maintenancePaymentModal');}
async function saveMaintenancePayment(event){
  event.preventDefault();const form=event.currentTarget,job=findJob(form.elements.jobId.value);if(!job)return;const paymentId=form.elements.paymentId.value,amount=Math.max(0,parseAmount(form.elements.amount.value)),current=payments(job),otherPaid=current.filter(row=>row.id!==paymentId).reduce((sum,row)=>sum+row.amount,0),total=summary(job).principal;if(!(amount>0)){alert('أدخل مبلغ الدفعة.');return}if(otherPaid+amount>total+0.009){alert(`الدفعة تتجاوز المتبقي. الحد الأعلى لهذه الدفعة ${money(Math.max(0,total-otherPaid))}.`);return}
  const old=current.find(row=>row.id===paymentId)||null,newPaymentId=old?.id||uid(),linked=findMaintenanceExpense(newPaymentId);if(linked.length>1){alert('وجد النظام أكثر من حركة مصروف مرتبطة بهذه الدفعة. لم يتم التعديل لحماية الرصيد، وتحتاج الحالة مراجعة مالية.');return}const expense=linked[0]||null,expenseId=expense?.id||old?.expenseId||uid(),row={id:newPaymentId,amount,date:form.elements.date.value||today(),note:String(form.elements.note.value||'').trim(),expenseId,createdAt:old?.createdAt||now(),updatedAt:now()},expenseRow={id:expenseId,ref:expense?.ref||expenseReference(),title:`دفعة صيانة: ${job.title} — ${job.vendor}`,amount,date:row.date,cat:'صيانة',category:'صيانة',expenseType:'maintenance_payment',sourceType:'maintenance',maintenanceJobId:job.id,maintenancePaymentId:row.id,paymentMethod:expense?.paymentMethod||'غير محدد',externalRef:expense?.externalRef||'',notes:row.note,note:row.note,createdAt:expense?.createdAt||now(),updatedAt:now()};if(expense)Object.assign(expense,expenseRow);else expenses().push(expenseRow);job.payments=old?current.map(item=>item.id===row.id?row:item):[...current,row];job.updatedAt=now();addAudit(old?'تعديل':'إضافة','دفعة صيانة',`${job.title} — ${money(amount)}`,old,row);closeModal('maintenancePaymentModal');await persistFinance();
}
async function deleteMaintenancePayment(jobId,paymentId){const job=findJob(jobId),payment=payments(job).find(row=>row.id===paymentId);if(!job||!payment)return;const linked=findMaintenanceExpense(paymentId);if(linked.length!==1){alert(`تعذر الحذف الآمن: الدفعة مرتبطة بـ ${linked.length} حركة مصروف بدل حركة واحدة. لم يتغير أي مبلغ.`);return}if(!confirm(`حذف دفعة الصيانة ${money(payment.amount)}؟ سيعود المبلغ إلى الرصيد ويزداد المتبقي.`))return;job.payments=payments(job).filter(row=>row.id!==paymentId);db.expenses=expenses().filter(row=>row.id!==linked[0].id);job.updatedAt=now();addAudit('حذف','دفعة صيانة',`${job.title} — ${money(payment.amount)}`,payment,null);await persistFinance();}

function openSalaryExpense(id=''){installModals();const salary=id?findSalary(id):null,form=document.getElementById('salaryExpenseForm');form.reset();form.elements.id.value=salary?.id||'';form.elements.worker.value=salary?.workerName||String(salary?.title||'').replace(/^راتب العامل:\s*/,'');form.elements.month.value=salary?.salaryMonth||today().slice(0,7);form.elements.amount.value=salary?.amount??'';form.elements.date.value=salary?.date||today();form.elements.note.value=salary?.notes||salary?.note||'';document.getElementById('salaryExpenseModalTitle').textContent=salary?'تعديل راتب عامل':'تسجيل راتب عامل';document.getElementById('deleteSalaryBtn').style.display=salary?'inline-flex':'none';openModal('salaryExpenseModal');}
async function saveSalaryExpense(event){
  event.preventDefault();const form=event.currentTarget,id=form.elements.id.value,old=id?findSalary(id):null,workerName=String(form.elements.worker.value||'').trim().replace(/\s+/g,' '),salaryMonth=form.elements.month.value,amount=Math.max(0,parseAmount(form.elements.amount.value));if(!workerName||!salaryMonth||!(amount>0)){alert('أدخل اسم العامل وشهر الراتب ومبلغًا صحيحًا.');return}const duplicate=Core?.isSalaryDuplicate?.(db,{workerName,salaryMonth,excludeId:id})??expenses().some(row=>row.id!==id&&row.expenseType==='salary'&&workerNameKey(row.workerName)===workerNameKey(workerName)&&row.salaryMonth===salaryMonth);let intentionalDuplicate=old?.intentionalDuplicate===true;if(duplicate){if(!confirm(`يوجد راتب مسجل للعامل ${workerName} عن شهر ${salaryMonth}.\n\nهل تريد تسجيل تكرار مقصود؟`))return;intentionalDuplicate=true}const row={id:old?.id||uid(),ref:old?.ref||expenseReference(),title:`راتب العامل: ${workerName}`,workerName,salaryMonth,amount,date:form.elements.date.value||today(),cat:'راتب عامل',category:'راتب عامل',expenseType:'salary',sourceType:'salary',paymentMethod:old?.paymentMethod||'غير محدد',externalRef:old?.externalRef||'',notes:String(form.elements.note.value||'').trim(),note:String(form.elements.note.value||'').trim(),intentionalDuplicate,createdAt:old?.createdAt||now(),updatedAt:now()},before=old?clone(old):null;if(old)Object.assign(old,row);else expenses().push(row);addAudit(old?'تعديل':'إضافة','راتب عامل',`${workerName} — ${salaryMonth} — ${money(amount)}`,before,row);closeModal('salaryExpenseModal');await persistFinance();
}
async function deleteSalaryExpense(){const id=document.getElementById('salaryExpenseForm')?.elements.id.value,old=findSalary(id);if(!old||!confirm(`حذف راتب ${old.workerName||''} عن شهر ${old.salaryMonth||''}؟ سيعود المبلغ إلى الرصيد.`))return;db.expenses=expenses().filter(row=>row.id!==id);addAudit('حذف','راتب عامل',`${old.workerName||''} — ${old.salaryMonth||''} — ${money(old.amount)}`,old,null);closeModal('salaryExpenseModal');await persistFinance();}

function openNote(id=''){installModals();const note=id?findNote(id):null,form=document.getElementById('accountingNoteForm');form.reset();form.elements.id.value=note?.id||'';form.elements.title.value=note?.title||'استلاف من حساب المنتجع';form.elements.principalAmount.value=note?.principalAmount??'';form.elements.date.value=note?.date||today();form.elements.note.value=note?.note||'';document.getElementById('accountingNoteModalTitle').textContent=note?'تعديل الملاحظة الحسابية':'إضافة ملاحظة حسابية';openModal('accountingNoteModal');}
async function saveAccountingNote(event){event.preventDefault();const form=event.currentTarget,id=form.elements.id.value,note=id?findNote(id):null,principalAmount=Math.max(0,parseAmount(form.elements.principalAmount.value)),alreadyPaid=note?summary(note).paid:0;if(!(principalAmount>0)){alert('أدخل أصل المبلغ.');return}if(principalAmount+0.009<alreadyPaid){alert(`لا يمكن جعل أصل المبلغ أقل من إجمالي ما تم سداده (${money(alreadyPaid)}).`);return}const next={id:note?.id||uid(),title:String(form.elements.title.value||'').trim()||'استلاف من حساب المنتجع',principalAmount,date:form.elements.date.value||today(),note:String(form.elements.note.value||'').trim(),payments:payments(note),createdAt:note?.createdAt||now(),updatedAt:now()},before=note?clone(note):null;if(note)Object.assign(note,next);else notes().push(next);addAudit(note?'تعديل':'إضافة','ملاحظة حسابية',`${next.title} — ${money(principalAmount)}`,before,next);closeModal('accountingNoteModal');await persistFinance();}
async function deleteNote(id){const note=findNote(id);if(!note||!confirm('حذف السلفة وسجل سدادها؟'))return;db.accountingNotes=notes().filter(row=>row.id!==id);addAudit('حذف','ملاحظة حسابية',note.title||'',note,null);await persistFinance();}
function openPayment(noteId,paymentId=''){installModals();const note=findNote(noteId);if(!note)return;const payment=payments(note).find(row=>row.id===paymentId)||null,form=document.getElementById('accountingPaymentForm');form.reset();form.elements.noteId.value=noteId;form.elements.paymentId.value=payment?.id||'';form.elements.amount.value=payment?.amount??'';form.elements.date.value=payment?.date||today();form.elements.note.value=payment?.note||'';document.getElementById('accountingPaymentModalTitle').textContent=payment?'تعديل السداد':'إضافة سداد';openModal('accountingPaymentModal');}
async function saveAccountingPayment(event){event.preventDefault();const form=event.currentTarget,note=findNote(form.elements.noteId.value);if(!note)return;const paymentId=form.elements.paymentId.value,amount=Math.max(0,parseAmount(form.elements.amount.value)),current=payments(note),otherPaid=current.filter(row=>row.id!==paymentId).reduce((sum,row)=>sum+row.amount,0),principal=summary(note).principal;if(!(amount>0)){alert('أدخل مبلغ السداد.');return}if(otherPaid+amount>principal+0.009){alert(`السداد يتجاوز المتبقي. الحد الأعلى لهذه الدفعة ${money(Math.max(0,principal-otherPaid))}.`);return}const old=current.find(row=>row.id===paymentId)||null,row={id:old?.id||uid(),amount,date:form.elements.date.value||today(),note:String(form.elements.note.value||'').trim(),createdAt:old?.createdAt||now(),updatedAt:now()};note.payments=old?current.map(item=>item.id===row.id?row:item):[...current,row];note.updatedAt=now();addAudit(old?'تعديل':'إضافة','سداد ملاحظة حسابية',`${note.title} — ${money(amount)}`,old,row);closeModal('accountingPaymentModal');await persistFinance();}
async function deletePayment(noteId,paymentId){const note=findNote(noteId),row=payments(note).find(item=>item.id===paymentId);if(!note||!row||!confirm(`حذف سداد ${money(row.amount)}؟ سيعاد المبلغ إلى المتبقي.`))return;note.payments=payments(note).filter(item=>item.id!==paymentId);note.updatedAt=now();addAudit('حذف','سداد ملاحظة حسابية',`${note.title} — ${money(row.amount)}`,row,null);await persistFinance();}

function wrapOrdinaryExpenseEditor(){const original=window.openExpense;if(typeof original!=='function'||original.__financeSourcesWrapped)return;const wrapped=function(id){const row=id?expenses().find(item=>item.id===id):null;if(row?.maintenancePaymentId){openMaintenancePayment(row.maintenanceJobId,row.maintenancePaymentId);return}if(isSalary(row)){openSalaryExpense(row.id);return}return original.apply(this,arguments)};wrapped.__financeSourcesWrapped=true;window.openExpense=wrapped;}
function install(){preserveMaintenanceState();installStyles();renderAllFinanceTools();wrapOrdinaryExpenseEditor();const base=window.renderExpenses;if(typeof base==='function'&&!base.__financeOrganizer){const wrapped=function(){const result=base.apply(this,arguments);setTimeout(renderAllFinanceTools,0);return result};wrapped.__financeOrganizer=true;window.renderExpenses=wrapped;}}

window.openMaintenanceJob=openMaintenanceJob;window.deleteMaintenanceJob=deleteMaintenanceJob;window.openMaintenancePayment=openMaintenancePayment;window.deleteMaintenancePayment=deleteMaintenancePayment;window.openSalaryExpense=openSalaryExpense;window.deleteSalaryExpense=deleteSalaryExpense;
window.openAccountingNote=openNote;window.deleteAccountingNote=deleteNote;window.openAccountingPayment=openPayment;window.deleteAccountingPayment=deletePayment;window.renderAccountingNotes=renderAllFinanceTools;
window.AccountingNotes={summary,payments};window.FinanceOrganizer={summary,render:renderAllFinanceTools};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
